/**
 * SMART JABAR — Input Validation & Sanitization Helpers
 * 
 * Provides client-side input sanitization and validation utilities
 * to enhance user experience and maintain data cleanliness before sending requests.
 */

/**
 * Sanitizes generic user text input by trimming whitespace
 * and stripping potentially malicious HTML tags or script injection patterns.
 */
export function sanitizeString(input: string | undefined | null): string {
  if (!input) return ''
  return input
    .trim()
    .replace(/[<>]/g, '') // Strip angle brackets to prevent unescaped HTML injection
}

/**
 * Validates Indonesian ASN NIP format (18 numeric digits, e.g. 198503152010011002)
 * or general numeric identifier.
 */
export function isValidNip(nip: string): boolean {
  const clean = nip.trim()
  return /^\d{18}$/.test(clean) || /^\d{8,18}$/.test(clean)
}

/**
 * Validates URLs ensuring strict http or https protocols.
 * Rejects javascript:, data:, or malformed protocols.
 */
export function isValidUrl(url: string, allowRelative = false): boolean {
  if (!url || typeof url !== 'string') return false
  const trimmed = url.trim()

  if (allowRelative && trimmed.startsWith('/')) {
    return true
  }

  try {
    const parsed = new URL(trimmed)
    return parsed.protocol === 'http:' || parsed.protocol === 'https:'
  } catch {
    return false
  }
}

/**
 * Validates image sources (HTTP/HTTPS URLs, relative paths, Blob URLs,
 * or safe base64 Data URLs generated by FileReader during client preview/upload).
 */
export function isValidImageUrl(url: string | undefined | null): boolean {
  if (!url || typeof url !== 'string') return false
  const trimmed = url.trim()

  // 1. Relative paths (e.g. /logo-layanan/sidebar.webp)
  if (trimmed.startsWith('/') || trimmed.startsWith('./')) {
    return true
  }

  // 2. Base64 Image Data URLs (e.g. data:image/png;base64,...)
  if (/^data:image\/(png|jpeg|jpg|webp|svg\+xml|gif);base64,/i.test(trimmed)) {
    return true
  }

  // 3. Blob URLs (e.g. blob:http://localhost:5173/...)
  if (trimmed.startsWith('blob:')) {
    return true
  }

  // 4. Standard HTTP/HTTPS URLs
  try {
    const parsed = new URL(trimmed)
    return parsed.protocol === 'http:' || parsed.protocol === 'https:'
  } catch {
    return false
  }
}

/**
 * Validates email format.
 */
export function isValidEmail(email: string): boolean {
  if (!email || typeof email !== 'string') return false
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
  return emailRegex.test(email.trim())
}

/**
 * Checks string length limits.
 */
export function isWithinLength(str: string, min = 0, max = 255): boolean {
  const len = (str || '').trim().length
  return len >= min && len <= max
}
